name: ayuntamiento_gerindote
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.8
  carousel_slider: ^5.0.0
  http: ^1.2.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.2.6
  image_picker: ^1.0.7
  flutter_stripe: ^9.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


assets:
  - lib/assets/gerindote.png
  - lib/assets/icon_editarUsuario.png
  - lib/assets/icon_ajustesUsuario.png
  - lib/assets/icon_ayudaUsuario.png
  - lib/assets/icon_cerrarSesion.png
  - lib/assets/icon_historialCitasUsuario.png
  - lib/assets/icon_notificacionUsuario.png
  - lib/assets/icon_pagosUsuario.png
